### ISSUE TITLE
Main UI Popup Redesign

### ISSUE THREAD

**Issue by jshen340** [jshen340/uniBuzzy-GaTech-Team#18]
#### What is this task for
- Redesign the popup UI to have a more user-friendly flow and more aesthetically appealing and cohesive
#### What do you need to complete this
- N/A
#### What does complete look like
- [x] Finished Figma file ready for feedback and evaluation
####  Steps to complete
- [x] Style guide
- [x] Text description
- [x]  Figma

**Comment by ayang351** [comment]
Link to Figma File: https://www.figma.com/file/XmwHrslfnVTjqU4WIEPLmu/Pop-up-design?type=design&node-id=0%3A1&mode=design&t=ZGvKswTtM1fyrQI7-1 

**General design notes + decisions are in the comments**
